sudo: false
language: node_js
node_js: stable
env:
  global:
    - GH_USER_EMAIL="azu@users.noreply.github.com"
    - GH_USER_NAME="azu"
before_script:
  - |
    $(npm bin)/set-up-ssh --key "$encrypted_609327fcaff0_key" \
    --iv "$encrypted_609327fcaff0_iv" \
    --path-encrypted-key ".travis/github_deploy_key.enc"
script:
  - yarn test
  - if [ "${TRAVIS_EVENT_TYPE}" = "cron" ]; then node ./get-proposal.js && git add static && git commit -m "update data" && git push; fi
  - $(npm bin)/update-branch --commands "yarn run build" --commit-message "Deploy WebSite [skip ci]" --directory "build" --distribution-branch "gh-pages" --source-branch "master"
