sudo: false
language: node_js
node_js: stable
before_script:
  - |
    $(npm bin)/set-up-ssh --key "$encrypted_609327fcaff0_key" \
    --iv "$encrypted_609327fcaff0_iv" \
    --path-encrypted-key ".travis/github_deploy_key.enc"
  - |
    git config --global user.email "travis@travis-ci.org"
    git config --global user.name "Travis CI"
jobs:
  include:
    - stage: Build
      script:
        - yarn test
        - $(npm bin)/update-branch --commands "yarn run build" --commit-message "Deploy WebSite [skip ci]" --directory "build" --distribution-branch "gh-pages" --source-branch "master"
    - stage: 'Update data'
      if: type = cron
      script:
        - git checkout master
        - node ./get-proposal.js
        - bash .travis/push-if-update.sh static/
